/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as HistoryRouteImport } from "./routes/history";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as SetupRouteImport } from "./routes/setup";

const SetupRoute = SetupRouteImport.update({
  id: "/setup",
  path: "/setup",
  getParentRoute: () => rootRouteImport,
} as any);
const HistoryRoute = HistoryRouteImport.update({
  id: "/history",
  path: "/history",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/history": typeof HistoryRoute;
  "/setup": typeof SetupRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/history": typeof HistoryRoute;
  "/setup": typeof SetupRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/history": typeof HistoryRoute;
  "/setup": typeof SetupRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/history" | "/setup";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/history" | "/setup";
  id: "__root__" | "/" | "/history" | "/setup";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  HistoryRoute: typeof HistoryRoute;
  SetupRoute: typeof SetupRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/setup": {
      id: "/setup";
      path: "/setup";
      fullPath: "/setup";
      preLoaderRoute: typeof SetupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/history": {
      id: "/history";
      path: "/history";
      fullPath: "/history";
      preLoaderRoute: typeof HistoryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  SetupRoute: SetupRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
